### ISSUE TITLE
Error while build

### ISSUE THREAD

**Issue by deepseapua** [alvareztech/Pokedex#2]
/AndroidStudioProjects/Pokedex/app/src/main/java/tech/alvarez/pokedex/ListaPokemonAdapter.java:44: error: cannot access Fragment
        Glide.with(context)
             ^
  class file for android.support.v4.app.Fragment not found

To fix:
    //implementation 'com.github.bumptech.glide:glide:3.7.0'
    implementation 'com.github.bumptech.glide:glide:4.11.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.11.0'

  Glide.with(context)
                .load("https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/" + p.getNumber() + ".png")
                .centerCrop()
                //.crossFade()
                .diskCacheStrategy(DiskCacheStrategy.ALL)
                .into(holder.fotoImageView);

**Comment by alvareztech** [comment]
Thank you for reporting, sorry for updating it years later 🙁
